In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("../backend/dataset/car_rental_cleaned.csv")
df

,Car_ID,Brand,Model,Fuel_Type,Transmission,Body_Type,Mileage,Engine_CC,Year
0,1,Kia,EV6,Electric,Automatic,SUV,0,0,2024
1,2,Honda,Amaze,Diesel,Automatic,Sedan,20,1199,2019
2,3,Honda,Amaze,Diesel,Manual,Sedan,20,1199,2018
3,4,Honda,Amaze,Petrol,Manual,Sedan,20,1199,2024
4,5,Toyota,Innova,Diesel,Manual,SUV,14,2393,2018
...,...,...,...,...,...,...,...,...,...
9995,9996,Hyundai,Creta,Petrol,Automatic,SUV,19,1497,2023
9996,9997,Maruti,Swift,Petrol,Automatic,Hatchback,24,1197,2016
9997,9998,BMW,X1,Petrol,Automatic,SUV,16,1995,2020
9998,9999,Hyundai,Creta,Petrol,Manual,SUV,15,1497,2022
9999,10000,BMW,X1,Diesel,Automatic,SUV,13,1995,2019

In [3]:
categories=df.select_dtypes(include=['str']).columns
categories

Index(['Brand', 'Model', 'Fuel_Type', 'Transmission', 'Body_Type'], dtype='str')

In [4]:
numeric=df.select_dtypes(include=['int','float']).columns
numeric

Index(['Car_ID', 'Mileage', 'Engine_CC', 'Year'], dtype='str')

In [5]:
for i in categories:
    df[i]=df[i].str.lower().str.strip()
df[categories]

        Brand   Model Fuel_Type Transmission  Body_Type
0         kia     ev6  electric    automatic        suv
1       honda   amaze    diesel    automatic      sedan
2       honda   amaze    diesel       manual      sedan
3       honda   amaze    petrol       manual      sedan
4      toyota  innova    diesel       manual        suv
...       ...     ...       ...          ...        ...
9995  hyundai   creta    petrol    automatic        suv
9996   maruti   swift    petrol    automatic  hatchback
9997      bmw      x1    petrol    automatic        suv
9998  hyundai   creta    petrol       manual        suv
9999      bmw      x1    diesel    automatic        suv

[10000 rows x 5 columns]

In [6]:
df[numeric].describe()

            Car_ID       Mileage     Engine_CC          Year
count  10000.00000  10000.000000  10000.000000  10000.000000
mean    5000.50000     16.657000   1477.890100   2019.982100
std     2886.89568      5.993158    660.158157      2.571389
min        1.00000      0.000000      0.000000   2016.000000
25%     2500.75000     14.000000   1197.000000   2018.000000
50%     5000.50000     18.000000   1497.000000   2020.000000
75%     7500.25000     21.000000   1995.000000   2022.000000
max    10000.00000     26.000000   2755.000000   2024.000000

In [7]:
df.to_csv("../backend/dataset/car_rental_cbf.csv", index=False)

In [8]:
df1=pd.read_csv("../backend/dataset/car_rental_cbf.csv")
df1

,Car_ID,Brand,Model,Fuel_Type,Transmission,Body_Type,Mileage,Engine_CC,Year
0,1,kia,ev6,electric,automatic,suv,0,0,2024
1,2,honda,amaze,diesel,automatic,sedan,20,1199,2019
2,3,honda,amaze,diesel,manual,sedan,20,1199,2018
3,4,honda,amaze,petrol,manual,sedan,20,1199,2024
4,5,toyota,innova,diesel,manual,suv,14,2393,2018
...,...,...,...,...,...,...,...,...,...
9995,9996,hyundai,creta,petrol,automatic,suv,19,1497,2023
9996,9997,maruti,swift,petrol,automatic,hatchback,24,1197,2016
9997,9998,bmw,x1,petrol,automatic,suv,16,1995,2020
9998,9999,hyundai,creta,petrol,manual,suv,15,1497,2022
9999,10000,bmw,x1,diesel,automatic,suv,13,1995,2019

In [9]:
category=df1.select_dtypes(include=['str']).columns
category
df[category].isnull().sum()

Brand           0
Model           0
Fuel_Type       0
Transmission    0
Body_Type       0
dtype: int64

In [10]:
numerics=df1.select_dtypes(include=['int','float']).columns
numerics

Index(['Car_ID', 'Mileage', 'Engine_CC', 'Year'], dtype='str')

In [11]:
df1["feature_text"] = df1[category].astype(str).agg(" ".join, axis=1)
df1["feature_text"]

0                kia ev6 electric automatic suv
1            honda amaze diesel automatic sedan
2               honda amaze diesel manual sedan
3               honda amaze petrol manual sedan
4               toyota innova diesel manual suv
                         ...
9995         hyundai creta petrol automatic suv
9996    maruti swift petrol automatic hatchback
9997                bmw x1 petrol automatic suv
9998            hyundai creta petrol manual suv
9999                bmw x1 diesel automatic suv
Name: feature_text, Length: 10000, dtype: str

TF IDF Vectorization

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
tfidf = TfidfVectorizer()

In [14]:
car_tfidf_matrix = tfidf.fit_transform(df1["feature_text"])

In [15]:
car_tfidf_matrix.shape

(10000, 28)

In [16]:
car_tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50000 stored elements and shape (10000, 28)>

In [17]:
tfidf.get_feature_names_out()

array(['alto', 'amaze', 'automatic', 'bmw', 'city', 'creta', 'diesel',
       'electric', 'ev6', 'fortuner', 'glanza', 'hatchback', 'honda',
       'hyundai', 'i20', 'innova', 'kia', 'manual', 'maruti', 'petrol',
       'sedan', 'seltos', 'series', 'suv', 'swift', 'toyota', 'verna',
       'x1'], dtype=object)

In [18]:
tfidf_df=pd.DataFrame(car_tfidf_matrix.toarray(),columns=tfidf.get_feature_names_out())
tfidf_df

,alto,amaze,automatic,bmw,city,creta,diesel,electric,ev6,fortuner,...,maruti,petrol,sedan,seltos,series,suv,swift,toyota,verna,x1
0,0.0,0.000000,0.245329,0.000000,0.0,0.000000,0.000000,0.567886,0.567886,0.0,...,0.00000,0.000000,0.000000,0.0,0.0,0.289920,0.000000,0.000000,0.0,0.000000
1,0.0,0.627656,0.264262,0.000000,0.0,0.000000,0.361936,0.000000,0.000000,0.0,...,0.00000,0.000000,0.385460,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000
2,0.0,0.618316,0.000000,0.000000,0.0,0.000000,0.356550,0.000000,0.000000,0.0,...,0.00000,0.000000,0.379724,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000
3,0.0,0.638722,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.00000,0.261848,0.392256,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000
4,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.380305,0.000000,0.000000,0.0,...,0.00000,0.000000,0.000000,0.0,0.0,0.328143,0.000000,0.458774,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.000000,0.293716,0.000000,0.0,0.690537,0.000000,0.000000,0.000000,0.0,...,0.00000,0.285991,0.000000,0.0,0.0,0.347101,0.000000,0.000000,0.0,0.000000
9996,0.0,0.000000,0.276787,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.52159,0.269507,0.000000,0.0,0.0,0.000000,0.644552,0.000000,0.0,0.000000
9997,0.0,0.000000,0.284163,0.535741,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.00000,0.276689,0.000000,0.0,0.0,0.335812,0.000000,0.000000,0.0,0.665512
9998,0.0,0.000000,0.000000,0.000000,0.0,0.677909,0.000000,0.000000,0.000000,0.0,...,0.00000,0.280761,0.000000,0.0,0.0,0.340753,0.000000,0.000000,0.0,0.000000
9999,0.0,0.000000,0.274082,0.516735,0.0,0.000000,0.375386,0.000000,0.000000,0.0,...,0.00000,0.000000,0.000000,0.0,0.0,0.323899,0.000000,0.000000,0.0,0.641902

Cosine Similarity

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
def build_user_profile(user_preferences, tfidf):
    """    Converts user-selected categorical preferences into a TF-IDF vector
    """
    user_text = (
        user_preferences["Brand"] + " " +
        user_preferences["Fuel_Type"] + " " +
        user_preferences["Transmission"] + " " +
        user_preferences["Body_Type"]
    )
    
    user_vector = tfidf.transform([user_text])
    return user_vector

In [21]:
def apply_numeric_filters(df1, preferences):
    """
    Apply numeric filters: Mileage and Engine_CC only
    """

    filtered_df = df1.copy()

    # Minimum mileage
    if "min_mileage" in preferences and preferences["min_mileage"] is not None:
        filtered_df = filtered_df[
            filtered_df["Mileage"] >= preferences["min_mileage"]
        ]

    # Maximum engine capacity
    if "max_engine_cc" in preferences and preferences["max_engine_cc"] is not None:
        filtered_df = filtered_df[
            filtered_df["Engine_CC"] <= preferences["max_engine_cc"]
        ]

    return filtered_df

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_cbf(
    user_preferences,
    df1,
    car_tfidf_matrix,
    tfidf,
    top_n=5
):
    # 1. Build user preference text
    user_text = (
        user_preferences["Brand"] + " " +
        user_preferences["Fuel_Type"] + " " +
        user_preferences["Transmission"] + " " +
        user_preferences["Body_Type"]
    )

    user_vector = tfidf.transform([user_text])

    # 2. Compute cosine similarity
    similarity_scores = cosine_similarity(
        user_vector,
        car_tfidf_matrix
    )[0]

    df1 = df1.copy()
    df["similarity_score"] = similarity_scores

    # 3. Apply numeric filters (Mileage + CC)
    df_filtered = apply_numeric_filters(df1, user_preferences)

    # 4. Rank and return Top-N
    recommendations = df_filtered.sort_values(
        by="similarity_score",
        ascending=False
    ).head(top_n)

    return recommendations[[
        "Car_ID",
        "Brand",
        "Model",
        "Fuel_Type",
        "Transmission",
        "Body_Type",
        "Mileage",
        "Engine_CC",
        "similarity_score"
    ]]